"""Append additional tickers to TICKERS list — generated to expand Apple Stocks coverage."""

# Format: (symbol, name, sector_or_None)
EXTRA_TICKERS = [
    # ============ ADDITIONAL S&P 500 / Russell 1000 ============
    ("ABNB", "Airbnb Inc.", "Consumer Cyclical"), ("ACGL", "Arch Capital Group", "Financial Services"),
    ("ADM", "Archer-Daniels-Midland", "Consumer Defensive"), ("AEE", "Ameren Corp.", "Utilities"),
    ("AES", "AES Corp.", "Utilities"), ("AFLAC", "Aflac Inc.", "Financial Services"),
    ("AKAM", "Akamai Technologies", "Technology"), ("ALB", "Albemarle Corp.", "Basic Materials"),
    ("ALK", "Alaska Air Group", "Industrials"), ("ALLE", "Allegion plc", "Industrials"),
    ("AMCR", "Amcor plc", "Basic Materials"), ("AMP", "Ameriprise Financial", "Financial Services"),
    ("ANET", "Arista Networks", "Technology"), ("AOS", "A.O. Smith Corp.", "Industrials"),
    ("APA", "APA Corp.", "Energy"), ("APTV", "Aptiv plc", "Consumer Cyclical"),
    ("ARMK", "Aramark", "Consumer Cyclical"), ("ATVI", "Activision Blizzard", "Communication Services"),
    ("AVY", "Avery Dennison Corp.", "Industrials"), ("AWI", "Armstrong World Industries", "Industrials"),
    ("AXON", "Axon Enterprise", "Industrials"), ("BALL", "Ball Corp.", "Industrials"),
    ("BBWI", "Bath & Body Works", "Consumer Cyclical"), ("BEN", "Franklin Resources", "Financial Services"),
    ("BF.B", "Brown-Forman Class B", "Consumer Defensive"), ("BG", "Bunge Global", "Consumer Defensive"),
    ("BIO", "Bio-Rad Laboratories", "Healthcare"), ("BKR", "Baker Hughes Co.", "Energy"),
    ("BLDR", "Builders FirstSource", "Industrials"), ("BR", "Broadridge Financial Solutions", "Technology"),
    ("BWA", "BorgWarner Inc.", "Consumer Cyclical"), ("BXP", "Boston Properties", "Real Estate"),
    ("CAG", "Conagra Brands", "Consumer Defensive"), ("CBOE", "Cboe Global Markets", "Financial Services"),
    ("CCEP", "Coca-Cola Europacific Partners", "Consumer Defensive"),
    ("CCL", "Carnival Corp.", "Consumer Cyclical"), ("CDAY", "Ceridian HCM Holding", "Technology"),
    ("CE", "Celanese Corp.", "Basic Materials"), ("CF", "CF Industries Holdings", "Basic Materials"),
    ("CFG", "Citizens Financial", "Financial Services"), ("CHD", "Church & Dwight", "Consumer Defensive"),
    ("CHRW", "C.H. Robinson Worldwide", "Industrials"), ("CL", "Colgate-Palmolive", "Consumer Defensive"),
    ("CLF", "Cleveland-Cliffs", "Basic Materials"), ("CLX", "Clorox Co.", "Consumer Defensive"),
    ("CMA", "Comerica Inc.", "Financial Services"), ("CMS", "CMS Energy", "Utilities"),
    ("CNC", "Centene Corp.", "Healthcare"), ("CNXC", "Concentrix Corp.", "Technology"),
    ("CPB", "Campbell Soup Co.", "Consumer Defensive"), ("CPRT", "Copart Inc.", "Industrials"),
    ("CPT", "Camden Property Trust", "Real Estate"), ("CRL", "Charles River Laboratories", "Healthcare"),
    ("CTLT", "Catalent Inc.", "Healthcare"), ("CTRA", "Coterra Energy", "Energy"),
    ("CVS", "CVS Health Corp.", "Healthcare"), ("CZR", "Caesars Entertainment", "Consumer Cyclical"),
    ("DAY", "Dayforce Inc.", "Technology"), ("DECK", "Deckers Outdoor", "Consumer Cyclical"),
    ("DFS", "Discover Financial Services", "Financial Services"), ("DG", "Dollar General", "Consumer Defensive"),
    ("DHI", "D.R. Horton", "Consumer Cyclical"), ("DPZ", "Domino's Pizza", "Consumer Cyclical"),
    ("DRI", "Darden Restaurants", "Consumer Cyclical"), ("DVA", "DaVita Inc.", "Healthcare"),
    ("DXC", "DXC Technology", "Technology"), ("EG", "Everest Group", "Financial Services"),
    ("EIX", "Edison International", "Utilities"), ("EL", "Estee Lauder Companies", "Consumer Defensive"),
    ("ENPH", "Enphase Energy", "Technology"), ("EPAM", "EPAM Systems", "Technology"),
    ("EQT", "EQT Corp.", "Energy"), ("ERIE", "Erie Indemnity", "Financial Services"),
    ("ESS", "Essex Property Trust", "Real Estate"), ("ETSY", "Etsy Inc.", "Consumer Cyclical"),
    ("EVRG", "Evergy Inc.", "Utilities"), ("EXPE", "Expedia Group", "Consumer Cyclical"),
    ("FANG", "Diamondback Energy", "Energy"), ("FBHS", "Fortune Brands Home & Security", "Industrials"),
    ("FDS", "FactSet Research Systems", "Financial Services"), ("FFIV", "F5 Inc.", "Technology"),
    ("FICO", "Fair Isaac Corp.", "Technology"), ("FLT", "FLEETCOR Technologies", "Technology"),
    ("FMC", "FMC Corp.", "Basic Materials"), ("FOX", "Fox Corp. Class B", "Communication Services"),
    ("FOXA", "Fox Corp. Class A", "Communication Services"), ("FRT", "Federal Realty Investment Trust", "Real Estate"),
    ("FSLR", "First Solar Inc.", "Technology"), ("FTV", "Fortive Corp.", "Industrials"),
    ("GEN", "Gen Digital Inc.", "Technology"), ("GLW", "Corning Inc.", "Technology"),
    ("GNRC", "Generac Holdings", "Industrials"), ("GPC", "Genuine Parts Co.", "Consumer Cyclical"),
    ("GPN", "Global Payments Inc.", "Technology"), ("HAL", "Halliburton Co.", "Energy"),
    ("HAS", "Hasbro Inc.", "Consumer Cyclical"), ("HBAN", "Huntington Bancshares", "Financial Services"),
    ("HEI", "HEICO Corp.", "Industrials"), ("HII", "Huntington Ingalls Industries", "Industrials"),
    ("HRL", "Hormel Foods Corp.", "Consumer Defensive"), ("HSIC", "Henry Schein", "Healthcare"),
    ("HST", "Host Hotels & Resorts", "Real Estate"), ("HUBB", "Hubbell Inc.", "Industrials"),
    ("HWM", "Howmet Aerospace", "Industrials"), ("INCY", "Incyte Corp.", "Healthcare"),
    ("IP", "International Paper", "Basic Materials"), ("IPG", "Interpublic Group", "Communication Services"),
    ("IQV", "IQVIA Holdings", "Healthcare"), ("IR", "Ingersoll Rand", "Industrials"),
    ("IRM", "Iron Mountain", "Real Estate"), ("J", "Jacobs Solutions", "Industrials"),
    ("JBHT", "J.B. Hunt Transport Services", "Industrials"), ("JCI", "Johnson Controls International", "Industrials"),
    ("JKHY", "Jack Henry & Associates", "Technology"), ("JNPR", "Juniper Networks", "Technology"),
    ("K", "Kellanova", "Consumer Defensive"), ("KEY", "KeyCorp", "Financial Services"),
    ("KIM", "Kimco Realty", "Real Estate"), ("KMX", "CarMax Inc.", "Consumer Cyclical"),
    ("L", "Loews Corp.", "Financial Services"), ("LDOS", "Leidos Holdings", "Industrials"),
    ("LEN", "Lennar Corp.", "Consumer Cyclical"), ("LKQ", "LKQ Corp.", "Consumer Cyclical"),
    ("LNC", "Lincoln National", "Financial Services"), ("LNT", "Alliant Energy", "Utilities"),
    ("LUMN", "Lumen Technologies", "Communication Services"), ("LVS", "Las Vegas Sands", "Consumer Cyclical"),
    ("LW", "Lamb Weston Holdings", "Consumer Defensive"), ("MAA", "Mid-America Apartment Communities", "Real Estate"),
    ("MAS", "Masco Corp.", "Industrials"), ("MGM", "MGM Resorts International", "Consumer Cyclical"),
    ("MHK", "Mohawk Industries", "Consumer Cyclical"), ("MKC", "McCormick & Co.", "Consumer Defensive"),
    ("MKTX", "MarketAxess Holdings", "Financial Services"), ("MOH", "Molina Healthcare", "Healthcare"),
    ("MOS", "Mosaic Co.", "Basic Materials"), ("MPWR", "Monolithic Power Systems", "Technology"),
    ("MTCH", "Match Group", "Communication Services"), ("MTD", "Mettler-Toledo International", "Healthcare"),
    ("NDSN", "Nordson Corp.", "Industrials"), ("NEM", "Newmont Corp.", "Basic Materials"),
    ("NI", "NiSource Inc.", "Utilities"), ("NRG", "NRG Energy", "Utilities"),
    ("NTAP", "NetApp Inc.", "Technology"), ("NVR", "NVR Inc.", "Consumer Cyclical"),
    ("NWS", "News Corp Class B", "Communication Services"), ("NWSA", "News Corp Class A", "Communication Services"),
    ("O", "Realty Income Corp.", "Real Estate"), ("OKE", "ONEOK Inc.", "Energy"),
    ("OMC", "Omnicom Group", "Communication Services"), ("OXY", "Occidental Petroleum", "Energy"),
    ("PARA", "Paramount Global", "Communication Services"), ("PAYC", "Paycom Software", "Technology"),
    ("PEG", "Public Service Enterprise Group", "Utilities"), ("PFG", "Principal Financial Group", "Financial Services"),
    ("PHM", "PulteGroup Inc.", "Consumer Cyclical"), ("PKG", "Packaging Corp. of America", "Basic Materials"),
    ("PNR", "Pentair plc", "Industrials"), ("PNW", "Pinnacle West Capital", "Utilities"),
    ("POOL", "Pool Corp.", "Consumer Cyclical"), ("PPG", "PPG Industries", "Basic Materials"),
    ("PPL", "PPL Corp.", "Utilities"), ("PTC", "PTC Inc.", "Technology"),
    ("PWR", "Quanta Services", "Industrials"), ("QRVO", "Qorvo Inc.", "Technology"),
    ("RCL", "Royal Caribbean Cruises", "Consumer Cyclical"), ("REG", "Regency Centers", "Real Estate"),
    ("RF", "Regions Financial", "Financial Services"), ("RHI", "Robert Half Inc.", "Industrials"),
    ("RL", "Ralph Lauren Corp.", "Consumer Cyclical"), ("ROL", "Rollins Inc.", "Industrials"),
    ("ROST", "Ross Stores", "Consumer Cyclical"), ("RVTY", "Revvity Inc.", "Healthcare"),
    ("SBAC", "SBA Communications", "Real Estate"), ("SEDG", "SolarEdge Technologies", "Technology"),
    ("SJM", "J.M. Smucker Co.", "Consumer Defensive"), ("SNA", "Snap-on Inc.", "Industrials"),
    ("SOLV", "Solventum Corp.", "Healthcare"), ("STE", "STERIS plc", "Healthcare"),
    ("STX", "Seagate Technology", "Technology"), ("SWK", "Stanley Black & Decker", "Industrials"),
    ("SWKS", "Skyworks Solutions", "Technology"), ("SYF", "Synchrony Financial", "Financial Services"),
    ("TAP", "Molson Coors Beverage", "Consumer Defensive"), ("TDG", "TransDigm Group", "Industrials"),
    ("TDY", "Teledyne Technologies", "Technology"), ("TECH", "Bio-Techne Corp.", "Healthcare"),
    ("TER", "Teradyne Inc.", "Technology"), ("TFC", "Truist Financial", "Financial Services"),
    ("TFX", "Teleflex Inc.", "Healthcare"), ("TPR", "Tapestry Inc.", "Consumer Cyclical"),
    ("TRGP", "Targa Resources", "Energy"), ("TRMB", "Trimble Inc.", "Technology"),
    ("TSN", "Tyson Foods", "Consumer Defensive"), ("TXT", "Textron Inc.", "Industrials"),
    ("UA", "Under Armour Class C", "Consumer Cyclical"), ("UAA", "Under Armour Class A", "Consumer Cyclical"),
    ("UDR", "UDR Inc.", "Real Estate"), ("UHS", "Universal Health Services", "Healthcare"),
    ("ULTA", "Ulta Beauty", "Consumer Cyclical"), ("URI", "United Rentals", "Industrials"),
    ("VFC", "VF Corp.", "Consumer Cyclical"), ("VRSN", "VeriSign Inc.", "Technology"),
    ("VTRS", "Viatris Inc.", "Healthcare"), ("WAT", "Waters Corp.", "Healthcare"),
    ("WBA", "Walgreens Boots Alliance", "Healthcare"), ("WDC", "Western Digital", "Technology"),
    ("WEC", "WEC Energy Group", "Utilities"), ("WHR", "Whirlpool Corp.", "Consumer Cyclical"),
    ("WMB", "Williams Companies", "Energy"), ("WRB", "W.R. Berkley Corp.", "Financial Services"),
    ("WRK", "WestRock Co.", "Basic Materials"), ("WTW", "Willis Towers Watson", "Financial Services"),
    ("XYL", "Xylem Inc.", "Industrials"), ("YUM", "Yum! Brands", "Consumer Cyclical"),
    ("ZBRA", "Zebra Technologies", "Technology"),

    # ============ POPULAR MID/SMALL CAPS + MEME STOCKS ============
    ("AMC", "AMC Entertainment Holdings", "Communication Services"), ("GME", "GameStop Corp.", "Consumer Cyclical"),
    ("BB", "BlackBerry Ltd.", "Technology"), ("BBBY", "Bed Bath & Beyond", "Consumer Cyclical"),
    ("CHWY", "Chewy Inc.", "Consumer Cyclical"), ("DKNG", "DraftKings Inc.", "Consumer Cyclical"),
    ("ROKU", "Roku Inc.", "Communication Services"), ("U", "Unity Software", "Technology"),
    ("AFRM", "Affirm Holdings", "Financial Services"), ("UPST", "Upstart Holdings", "Financial Services"),
    ("SOFI", "SoFi Technologies", "Financial Services"), ("SOFI", "SoFi Technologies", "Financial Services"),
    ("RKT", "Rocket Companies", "Financial Services"), ("OPEN", "Opendoor Technologies", "Real Estate"),
    ("Z", "Zillow Group Class C", "Real Estate"), ("ZG", "Zillow Group Class A", "Real Estate"),
    ("RDFN", "Redfin Corp.", "Real Estate"), ("PTON", "Peloton Interactive", "Consumer Cyclical"),
    ("BYND", "Beyond Meat", "Consumer Defensive"), ("OATLY", "Oatly Group", "Consumer Defensive"),
    ("RIDE", "Lordstown Motors", "Consumer Cyclical"), ("FUBO", "fuboTV Inc.", "Communication Services"),
    ("CLOV", "Clover Health", "Healthcare"), ("WISH", "ContextLogic", "Consumer Cyclical"),
    ("SPCE", "Virgin Galactic Holdings", "Industrials"), ("BLNK", "Blink Charging", "Industrials"),
    ("FCEL", "FuelCell Energy", "Industrials"), ("NIO", "NIO Inc.", "Consumer Cyclical"),
    ("KOSS", "Koss Corp.", "Technology"), ("EXPR", "Express Inc.", "Consumer Cyclical"),
    ("NOK", "Nokia Oyj", "Technology"), ("SIRI", "Sirius XM Holdings", "Communication Services"),
    ("APE", "AMC Entertainment Preferred", "Communication Services"), ("MULN", "Mullen Automotive", "Consumer Cyclical"),
    ("BBIG", "Vinco Ventures", "Industrials"), ("PROG", "Progenity Inc.", "Healthcare"),
    ("WKHS", "Workhorse Group", "Consumer Cyclical"), ("RIDE", "Lordstown Motors", "Consumer Cyclical"),
    ("ATER", "Aterian Inc.", "Consumer Cyclical"), ("SDC", "SmileDirectClub", "Healthcare"),
    ("PLBY", "PLBY Group", "Consumer Cyclical"), ("TLRY", "Tilray Brands", "Healthcare"),
    ("CGC", "Canopy Growth", "Healthcare"), ("ACB", "Aurora Cannabis", "Healthcare"),
    ("SNDL", "SNDL Inc.", "Healthcare"), ("HEXO", "HEXO Corp.", "Healthcare"),
    ("CRON", "Cronos Group", "Healthcare"), ("OGI", "OrganiGram Holdings", "Healthcare"),
    ("CGC", "Canopy Growth Corp.", "Healthcare"),

    # ============ MORE TECH / GROWTH ============
    ("TWLO", "Twilio Inc.", "Technology"), ("ZBH", "Zimmer Biomet Holdings", "Healthcare"),
    ("PINS", "Pinterest Inc.", "Communication Services"), ("BMBL", "Bumble Inc.", "Communication Services"),
    ("RBLX", "Roblox Corp.", "Communication Services"), ("HOOD", "Robinhood Markets", "Financial Services"),
    ("SOUN", "SoundHound AI", "Technology"), ("AI", "C3.ai Inc.", "Technology"),
    ("BBAI", "BigBear.ai", "Technology"), ("PATH", "UiPath Inc.", "Technology"),
    ("S", "SentinelOne Inc.", "Technology"), ("ESTC", "Elastic N.V.", "Technology"),
    ("FSLY", "Fastly Inc.", "Technology"), ("GTLB", "GitLab Inc.", "Technology"),
    ("HCP", "HashiCorp Inc.", "Technology"), ("CFLT", "Confluent Inc.", "Technology"),
    ("BILL", "BILL Holdings", "Technology"), ("PD", "PagerDuty Inc.", "Technology"),
    ("ASAN", "Asana Inc.", "Technology"), ("MNDY", "monday.com Ltd.", "Technology"),
    ("APP", "AppLovin Corp.", "Technology"), ("TTD", "Trade Desk Inc.", "Technology"),
    ("TWTR", "Twitter Inc.", "Communication Services"), ("WORK", "Slack Technologies", "Technology"),
    ("PLTR", "Palantir Technologies", "Technology"), ("NTES", "NetEase Inc.", "Communication Services"),
    ("SEA", "Sea Ltd.", "Consumer Cyclical"), ("MELI", "MercadoLibre Inc.", "Consumer Cyclical"),
    ("STNE", "StoneCo Ltd.", "Technology"), ("PAGS", "PagSeguro Digital", "Technology"),
    ("GLOB", "Globant S.A.", "Technology"),

    # ============ INTERNATIONAL ADRs ============
    ("HMC", "Honda Motor Co.", "Consumer Cyclical"), ("TM", "Toyota Motor Corp.", "Consumer Cyclical"),
    ("SONY", "Sony Group Corp.", "Consumer Cyclical"), ("SMFG", "Sumitomo Mitsui Financial", "Financial Services"),
    ("MFG", "Mizuho Financial Group", "Financial Services"), ("NTT", "Nippon Telegraph & Telephone", "Communication Services"),
    ("ITUB", "Itau Unibanco Holding", "Financial Services"), ("PBR", "Petroleo Brasileiro", "Energy"),
    ("VALE", "Vale S.A.", "Basic Materials"), ("ABEV", "Ambev S.A.", "Consumer Defensive"),
    ("INFY", "Infosys Ltd.", "Technology"), ("WIT", "Wipro Ltd.", "Technology"),
    ("HDB", "HDFC Bank Ltd.", "Financial Services"), ("IBN", "ICICI Bank Ltd.", "Financial Services"),
    ("TTM", "Tata Motors Ltd.", "Consumer Cyclical"), ("RDY", "Dr. Reddy's Laboratories", "Healthcare"),
    ("E", "Eni S.p.A.", "Energy"), ("ENI", "Eni S.p.A.", "Energy"),
    ("EQNR", "Equinor ASA", "Energy"), ("STLA", "Stellantis N.V.", "Consumer Cyclical"),
    ("VWAGY", "Volkswagen AG ADR", "Consumer Cyclical"), ("MBGYY", "Mercedes-Benz Group ADR", "Consumer Cyclical"),
    ("BMWYY", "BMW AG ADR", "Consumer Cyclical"), ("BAYRY", "Bayer AG ADR", "Healthcare"),
    ("SIEGY", "Siemens AG ADR", "Industrials"), ("AIRBP", "Airbus SE ADR", "Industrials"),
    ("LVMUY", "LVMH Moet Hennessy", "Consumer Cyclical"), ("HEINY", "Heineken N.V.", "Consumer Defensive"),
    ("ABBNY", "ABB Ltd.", "Industrials"), ("NSRGY", "Nestle S.A.", "Consumer Defensive"),
    ("NTES", "NetEase Inc.", "Communication Services"), ("TCEHY", "Tencent Holdings ADR", "Communication Services"),
    ("BIDU", "Baidu Inc.", "Communication Services"), ("NTES", "NetEase Inc.", "Communication Services"),
    ("ASML", "ASML Holding N.V.", "Technology"), ("UMC", "United Microelectronics", "Technology"),
    ("ERIC", "Telefonaktiebolaget LM Ericsson", "Technology"), ("MT", "ArcelorMittal", "Basic Materials"),
    ("TEVA", "Teva Pharmaceutical Industries", "Healthcare"),

    # ============ ADDITIONAL ETFs (incl. leveraged) ============
    ("VUG", "Vanguard Growth ETF", None), ("VTV", "Vanguard Value ETF", None),
    ("MGK", "Vanguard Mega Cap Growth ETF", None), ("MGV", "Vanguard Mega Cap Value ETF", None),
    ("RSP", "Invesco S&P 500 Equal Weight ETF", None), ("MDY", "SPDR S&P MidCap 400 ETF", None),
    ("IJR", "iShares Core S&P Small-Cap ETF", None), ("IJH", "iShares Core S&P Mid-Cap ETF", None),
    ("VXF", "Vanguard Extended Market ETF", None), ("VBR", "Vanguard Small-Cap Value ETF", None),
    ("VBK", "Vanguard Small-Cap Growth ETF", None), ("VOT", "Vanguard Mid-Cap Growth ETF", None),
    ("VOE", "Vanguard Mid-Cap Value ETF", None),
    # Leveraged
    ("TQQQ", "ProShares UltraPro QQQ", None), ("SQQQ", "ProShares UltraPro Short QQQ", None),
    ("UPRO", "ProShares UltraPro S&P 500", None), ("SPXU", "ProShares UltraPro Short S&P 500", None),
    ("SPXL", "Direxion Daily S&P 500 Bull 3X", None), ("SPXS", "Direxion Daily S&P 500 Bear 3X", None),
    ("TNA", "Direxion Daily Small Cap Bull 3X", None), ("TZA", "Direxion Daily Small Cap Bear 3X", None),
    ("FAS", "Direxion Daily Financial Bull 3X", None), ("FAZ", "Direxion Daily Financial Bear 3X", None),
    ("LABU", "Direxion Daily S&P Biotech Bull 3X", None), ("LABD", "Direxion Daily S&P Biotech Bear 3X", None),
    ("SOXL", "Direxion Daily Semiconductor Bull 3X", None), ("SOXS", "Direxion Daily Semiconductor Bear 3X", None),
    ("WEBL", "Direxion Daily Dow Jones Internet Bull 3X", None), ("WEBS", "Direxion Daily Dow Jones Internet Bear 3X", None),
    ("CURE", "Direxion Daily Healthcare Bull 3X", None), ("DPST", "Direxion Daily Regional Banks Bull 3X", None),
    ("GUSH", "Direxion Daily S&P Oil & Gas Bull 2X", None), ("DRIP", "Direxion Daily S&P Oil & Gas Bear 2X", None),
    ("NUGT", "Direxion Daily Gold Miners Bull 2X", None), ("DUST", "Direxion Daily Gold Miners Bear 2X", None),
    ("YINN", "Direxion Daily FTSE China Bull 3X", None), ("YANG", "Direxion Daily FTSE China Bear 3X", None),
    # Thematic / Sector
    ("ICLN", "iShares Global Clean Energy ETF", None), ("TAN", "Invesco Solar ETF", None),
    ("LIT", "Global X Lithium & Battery Tech ETF", None), ("REMX", "VanEck Rare Earth/Strategic Metals", None),
    ("URA", "Global X Uranium ETF", None), ("WEAT", "Teucrium Wheat Fund", None),
    ("CORN", "Teucrium Corn Fund", None), ("DBA", "Invesco DB Agriculture Fund", None),
    ("DBC", "Invesco DB Commodity Index Tracking Fund", None), ("PDBC", "Invesco Optimum Yield Diversified Commodity", None),
    ("BOTZ", "Global X Robotics & Artificial Intelligence", None), ("ROBO", "ROBO Global Robotics & Automation", None),
    ("HACK", "ETFMG Prime Cyber Security ETF", None), ("CIBR", "First Trust NASDAQ Cybersecurity ETF", None),
    ("CLOU", "Global X Cloud Computing ETF", None), ("WCLD", "WisdomTree Cloud Computing Fund", None),
    ("FINX", "Global X FinTech ETF", None), ("ARKG", "ARK Genomic Revolution ETF", None),
    ("ARKF", "ARK Fintech Innovation ETF", None), ("ARKX", "ARK Space Exploration & Innovation", None),
    ("BLOK", "Amplify Transformational Data Sharing", None), ("SKYY", "First Trust Cloud Computing", None),
    ("SOXX", "iShares Semiconductor ETF", None), ("PSI", "Invesco Dynamic Semiconductors", None),
    ("ITA", "iShares U.S. Aerospace & Defense", None), ("PPA", "Invesco Aerospace & Defense", None),
    ("JETS", "U.S. Global Jets ETF", None), ("XOP", "SPDR S&P Oil & Gas Exploration", None),
    ("GDX", "VanEck Gold Miners ETF", None), ("GDXJ", "VanEck Junior Gold Miners ETF", None),
    ("PALL", "abrdn Physical Palladium Shares", None), ("PPLT", "abrdn Physical Platinum Shares", None),
    ("CPER", "United States Copper Index Fund", None), ("XME", "SPDR S&P Metals & Mining ETF", None),
    ("VPN", "Global X Data Center & Digital Infrastructure", None), ("BIL", "SPDR Bloomberg 1-3 Month T-Bill", None),
    ("SHY", "iShares 1-3 Year Treasury Bond ETF", None), ("IEF", "iShares 7-10 Year Treasury Bond", None),
    ("TIP", "iShares TIPS Bond ETF", None), ("MUB", "iShares National Muni Bond ETF", None),
    ("EMB", "iShares J.P. Morgan USD Emerging Markets Bond", None), ("PFF", "iShares Preferred & Income Securities", None),

    # ============ CRYPTO PAIRS (Yahoo Finance format) ============
    ("BTC-USD", "Bitcoin USD", "Crypto"), ("ETH-USD", "Ethereum USD", "Crypto"),
    ("SOL-USD", "Solana USD", "Crypto"), ("XRP-USD", "XRP USD", "Crypto"),
    ("ADA-USD", "Cardano USD", "Crypto"), ("DOGE-USD", "Dogecoin USD", "Crypto"),
    ("AVAX-USD", "Avalanche USD", "Crypto"), ("DOT-USD", "Polkadot USD", "Crypto"),
    ("MATIC-USD", "Polygon USD", "Crypto"), ("LINK-USD", "Chainlink USD", "Crypto"),
    ("LTC-USD", "Litecoin USD", "Crypto"), ("BCH-USD", "Bitcoin Cash USD", "Crypto"),
    ("ATOM-USD", "Cosmos USD", "Crypto"), ("UNI-USD", "Uniswap USD", "Crypto"),
    ("XLM-USD", "Stellar USD", "Crypto"), ("ALGO-USD", "Algorand USD", "Crypto"),
    ("NEAR-USD", "NEAR Protocol USD", "Crypto"), ("VET-USD", "VeChain USD", "Crypto"),
    ("ICP-USD", "Internet Computer USD", "Crypto"), ("FIL-USD", "Filecoin USD", "Crypto"),
    ("ETC-USD", "Ethereum Classic USD", "Crypto"), ("HBAR-USD", "Hedera USD", "Crypto"),
    ("APT-USD", "Aptos USD", "Crypto"), ("ARB-USD", "Arbitrum USD", "Crypto"),
    ("OP-USD", "Optimism USD", "Crypto"), ("INJ-USD", "Injective USD", "Crypto"),
    ("SUI-USD", "Sui USD", "Crypto"), ("TIA-USD", "Celestia USD", "Crypto"),
    ("SHIB-USD", "Shiba Inu USD", "Crypto"), ("PEPE-USD", "Pepe USD", "Crypto"),
    ("WIF-USD", "dogwifhat USD", "Crypto"), ("BONK-USD", "Bonk USD", "Crypto"),
    ("USDT-USD", "Tether USD", "Crypto"), ("USDC-USD", "USD Coin", "Crypto"),
    ("DAI-USD", "Dai USD", "Crypto"), ("BUSD-USD", "Binance USD", "Crypto"),

    # ============ INDICES ============
    ("^GSPC", "S&P 500 Index", "Index"), ("^DJI", "Dow Jones Industrial Average", "Index"),
    ("^IXIC", "NASDAQ Composite", "Index"), ("^RUT", "Russell 2000", "Index"),
    ("^VIX", "CBOE Volatility Index", "Index"), ("^FTSE", "FTSE 100", "Index"),
    ("^N225", "Nikkei 225", "Index"), ("^HSI", "Hang Seng Index", "Index"),
    ("^GDAXI", "DAX Performance-Index", "Index"), ("^FCHI", "CAC 40", "Index"),
    ("^STOXX50E", "EURO STOXX 50", "Index"), ("^BSESN", "S&P BSE SENSEX", "Index"),
    ("^NSEI", "NIFTY 50", "Index"), ("^TNX", "10-Year Treasury Yield", "Index"),
    ("^TYX", "30-Year Treasury Yield", "Index"),

    # ============ FOREX (Yahoo format with =X) ============
    ("EURUSD=X", "EUR/USD", "Currency"), ("GBPUSD=X", "GBP/USD", "Currency"),
    ("USDJPY=X", "USD/JPY", "Currency"), ("USDCHF=X", "USD/CHF", "Currency"),
    ("AUDUSD=X", "AUD/USD", "Currency"), ("USDCAD=X", "USD/CAD", "Currency"),
    ("NZDUSD=X", "NZD/USD", "Currency"), ("EURGBP=X", "EUR/GBP", "Currency"),
    ("EURJPY=X", "EUR/JPY", "Currency"), ("GBPJPY=X", "GBP/JPY", "Currency"),
    ("USDCNY=X", "USD/CNY", "Currency"), ("USDINR=X", "USD/INR", "Currency"),
    ("USDMXN=X", "USD/MXN", "Currency"), ("USDBRL=X", "USD/BRL", "Currency"),
    ("USDKRW=X", "USD/KRW", "Currency"), ("USDSGD=X", "USD/SGD", "Currency"),
    ("USDHKD=X", "USD/HKD", "Currency"), ("USDZAR=X", "USD/ZAR", "Currency"),
    ("USDTRY=X", "USD/TRY", "Currency"), ("USDRUB=X", "USD/RUB", "Currency"),

    # ============ COMMODITIES (Yahoo futures format) ============
    ("GC=F", "Gold Futures", "Commodity"), ("SI=F", "Silver Futures", "Commodity"),
    ("CL=F", "Crude Oil Futures", "Commodity"), ("BZ=F", "Brent Crude Oil Futures", "Commodity"),
    ("NG=F", "Natural Gas Futures", "Commodity"), ("HG=F", "Copper Futures", "Commodity"),
    ("PL=F", "Platinum Futures", "Commodity"), ("PA=F", "Palladium Futures", "Commodity"),
    ("ZC=F", "Corn Futures", "Commodity"), ("ZW=F", "Wheat Futures", "Commodity"),
    ("ZS=F", "Soybean Futures", "Commodity"), ("CT=F", "Cotton Futures", "Commodity"),
    ("KC=F", "Coffee Futures", "Commodity"), ("CC=F", "Cocoa Futures", "Commodity"),
    ("SB=F", "Sugar Futures", "Commodity"),
]
