"""Comprehensive ticker lookup list — S&P 500 + NASDAQ 100 + Dow 30 + popular ETFs (deduped).
Used for search, watchlist, alerts. Real prices fetched live via yfinance.
"""

# (symbol, name, sector) — sector may be None for ETFs/lookup-only entries
TICKERS = [
    # Mega-cap Tech
    ("AAPL", "Apple Inc.", "Technology"), ("MSFT", "Microsoft Corp.", "Technology"),
    ("GOOGL", "Alphabet Inc. Class A", "Technology"), ("GOOG", "Alphabet Inc. Class C", "Technology"),
    ("AMZN", "Amazon.com Inc.", "Consumer Cyclical"), ("NVDA", "NVIDIA Corp.", "Technology"),
    ("META", "Meta Platforms Inc.", "Communication Services"), ("TSLA", "Tesla Inc.", "Consumer Cyclical"),
    ("BRK.B", "Berkshire Hathaway B", "Financial Services"), ("AVGO", "Broadcom Inc.", "Technology"),
    ("LLY", "Eli Lilly & Co.", "Healthcare"), ("JPM", "JPMorgan Chase", "Financial Services"),
    ("V", "Visa Inc.", "Financial Services"), ("XOM", "Exxon Mobil", "Energy"),
    ("UNH", "UnitedHealth Group", "Healthcare"), ("MA", "Mastercard Inc.", "Financial Services"),
    ("PG", "Procter & Gamble", "Consumer Defensive"), ("JNJ", "Johnson & Johnson", "Healthcare"),
    ("HD", "Home Depot", "Consumer Cyclical"), ("COST", "Costco Wholesale", "Consumer Defensive"),
    ("ORCL", "Oracle Corp.", "Technology"), ("ABBV", "AbbVie Inc.", "Healthcare"),
    ("BAC", "Bank of America", "Financial Services"), ("CVX", "Chevron Corp.", "Energy"),
    ("MRK", "Merck & Co.", "Healthcare"), ("KO", "Coca-Cola Co.", "Consumer Defensive"),
    ("WMT", "Walmart Inc.", "Consumer Defensive"), ("NFLX", "Netflix Inc.", "Communication Services"),
    ("CRM", "Salesforce Inc.", "Technology"), ("AMD", "Advanced Micro Devices", "Technology"),
    ("PEP", "PepsiCo Inc.", "Consumer Defensive"), ("TMO", "Thermo Fisher Scientific", "Healthcare"),
    ("LIN", "Linde plc", "Basic Materials"), ("ADBE", "Adobe Inc.", "Technology"),
    ("CSCO", "Cisco Systems", "Technology"), ("WFC", "Wells Fargo & Co.", "Financial Services"),
    ("MCD", "McDonald's Corp.", "Consumer Cyclical"), ("ACN", "Accenture plc", "Technology"),
    ("ABT", "Abbott Laboratories", "Healthcare"), ("DIS", "Walt Disney Co.", "Communication Services"),
    ("DHR", "Danaher Corp.", "Healthcare"), ("VZ", "Verizon Communications", "Communication Services"),
    ("INTC", "Intel Corp.", "Technology"), ("QCOM", "Qualcomm Inc.", "Technology"),
    ("CAT", "Caterpillar Inc.", "Industrials"), ("TXN", "Texas Instruments", "Technology"),
    ("PFE", "Pfizer Inc.", "Healthcare"), ("INTU", "Intuit Inc.", "Technology"),
    ("AMGN", "Amgen Inc.", "Healthcare"), ("AMAT", "Applied Materials", "Technology"),
    ("MS", "Morgan Stanley", "Financial Services"), ("IBM", "IBM Corp.", "Technology"),
    ("NEE", "NextEra Energy", "Utilities"), ("GS", "Goldman Sachs", "Financial Services"),
    ("RTX", "RTX Corp.", "Industrials"), ("UNP", "Union Pacific", "Industrials"),
    ("HON", "Honeywell International", "Industrials"), ("LOW", "Lowe's Companies", "Consumer Cyclical"),
    ("PM", "Philip Morris International", "Consumer Defensive"), ("COP", "ConocoPhillips", "Energy"),
    ("UPS", "United Parcel Service", "Industrials"), ("BKNG", "Booking Holdings", "Consumer Cyclical"),
    ("GE", "General Electric", "Industrials"), ("AXP", "American Express", "Financial Services"),
    ("SPGI", "S&P Global", "Financial Services"), ("ELV", "Elevance Health", "Healthcare"),
    ("ISRG", "Intuitive Surgical", "Healthcare"), ("CMCSA", "Comcast Corp.", "Communication Services"),
    ("MDT", "Medtronic plc", "Healthcare"), ("LMT", "Lockheed Martin", "Industrials"),
    ("NOW", "ServiceNow Inc.", "Technology"), ("PLD", "Prologis Inc.", "Real Estate"),
    ("T", "AT&T Inc.", "Communication Services"), ("BA", "Boeing Co.", "Industrials"),
    ("BLK", "BlackRock Inc.", "Financial Services"), ("DE", "Deere & Co.", "Industrials"),
    ("SCHW", "Charles Schwab", "Financial Services"), ("SBUX", "Starbucks Corp.", "Consumer Cyclical"),
    ("ADI", "Analog Devices", "Technology"), ("GILD", "Gilead Sciences", "Healthcare"),
    ("MDLZ", "Mondelez International", "Consumer Defensive"), ("AMT", "American Tower", "Real Estate"),
    ("VRTX", "Vertex Pharmaceuticals", "Healthcare"), ("CB", "Chubb Ltd.", "Financial Services"),
    ("LRCX", "Lam Research", "Technology"), ("REGN", "Regeneron Pharmaceuticals", "Healthcare"),
    ("PANW", "Palo Alto Networks", "Technology"), ("MMC", "Marsh & McLennan", "Financial Services"),
    ("ETN", "Eaton Corp.", "Industrials"), ("CI", "Cigna Group", "Healthcare"),
    ("KLAC", "KLA Corp.", "Technology"), ("SO", "Southern Co.", "Utilities"),
    ("ZTS", "Zoetis Inc.", "Healthcare"), ("ANET", "Arista Networks", "Technology"),
    ("MO", "Altria Group", "Consumer Defensive"), ("DUK", "Duke Energy", "Utilities"),
    ("BDX", "Becton Dickinson", "Healthcare"), ("EQIX", "Equinix Inc.", "Real Estate"),
    ("ICE", "Intercontinental Exchange", "Financial Services"), ("CME", "CME Group", "Financial Services"),
    ("SHW", "Sherwin-Williams", "Basic Materials"), ("APD", "Air Products & Chemicals", "Basic Materials"),
    ("TJX", "TJX Companies", "Consumer Cyclical"), ("PYPL", "PayPal Holdings", "Financial Services"),
    ("CDNS", "Cadence Design Systems", "Technology"), ("SNPS", "Synopsys Inc.", "Technology"),
    ("MU", "Micron Technology", "Technology"), ("NKE", "Nike Inc.", "Consumer Cyclical"),
    ("ITW", "Illinois Tool Works", "Industrials"), ("GD", "General Dynamics", "Industrials"),
    ("CL", "Colgate-Palmolive", "Consumer Defensive"), ("WM", "Waste Management", "Industrials"),
    ("TGT", "Target Corp.", "Consumer Cyclical"), ("FCX", "Freeport-McMoRan", "Basic Materials"),
    ("EOG", "EOG Resources", "Energy"), ("MCK", "McKesson Corp.", "Healthcare"),
    ("ORLY", "O'Reilly Automotive", "Consumer Cyclical"), ("AON", "Aon plc", "Financial Services"),
    ("CSX", "CSX Corp.", "Industrials"), ("PNC", "PNC Financial Services", "Financial Services"),
    ("USB", "U.S. Bancorp", "Financial Services"), ("F", "Ford Motor Co.", "Consumer Cyclical"),
    ("GM", "General Motors", "Consumer Cyclical"), ("HUM", "Humana Inc.", "Healthcare"),
    ("EMR", "Emerson Electric", "Industrials"), ("APH", "Amphenol Corp.", "Technology"),
    ("MAR", "Marriott International", "Consumer Cyclical"), ("MSI", "Motorola Solutions", "Technology"),
    ("NSC", "Norfolk Southern", "Industrials"), ("FDX", "FedEx Corp.", "Industrials"),
    ("PSX", "Phillips 66", "Energy"), ("PSA", "Public Storage", "Real Estate"),
    ("MPC", "Marathon Petroleum", "Energy"), ("ROP", "Roper Technologies", "Technology"),
    ("AJG", "Arthur J. Gallagher", "Financial Services"), ("AZO", "AutoZone Inc.", "Consumer Cyclical"),
    ("SLB", "Schlumberger Ltd.", "Energy"), ("ADP", "Automatic Data Processing", "Industrials"),
    ("AFL", "Aflac Inc.", "Financial Services"), ("CARR", "Carrier Global", "Industrials"),
    ("HCA", "HCA Healthcare", "Healthcare"), ("AIG", "American International Group", "Financial Services"),
    ("OXY", "Occidental Petroleum", "Energy"), ("AEP", "American Electric Power", "Utilities"),
    ("D", "Dominion Energy", "Utilities"), ("WMB", "Williams Companies", "Energy"),
    ("KMB", "Kimberly-Clark", "Consumer Defensive"), ("TRV", "Travelers Companies", "Financial Services"),
    ("ECL", "Ecolab Inc.", "Basic Materials"), ("BSX", "Boston Scientific", "Healthcare"),
    ("SRE", "Sempra", "Utilities"), ("KMI", "Kinder Morgan", "Energy"),
    ("CTAS", "Cintas Corp.", "Industrials"), ("MET", "MetLife Inc.", "Financial Services"),
    ("PRU", "Prudential Financial", "Financial Services"), ("PCAR", "PACCAR Inc.", "Industrials"),
    ("NXPI", "NXP Semiconductors", "Technology"), ("CTSH", "Cognizant Technology", "Technology"),
    ("BX", "Blackstone Inc.", "Financial Services"), ("EW", "Edwards Lifesciences", "Healthcare"),
    ("CCI", "Crown Castle", "Real Estate"), ("VLO", "Valero Energy", "Energy"),
    ("TT", "Trane Technologies", "Industrials"), ("STZ", "Constellation Brands", "Consumer Defensive"),
    ("DLR", "Digital Realty Trust", "Real Estate"), ("MNST", "Monster Beverage", "Consumer Defensive"),
    ("CEG", "Constellation Energy", "Utilities"), ("FTNT", "Fortinet Inc.", "Technology"),
    ("EXC", "Exelon Corp.", "Utilities"), ("HLT", "Hilton Worldwide", "Consumer Cyclical"),
    ("ROST", "Ross Stores", "Consumer Cyclical"), ("CMG", "Chipotle Mexican Grill", "Consumer Cyclical"),
    ("GIS", "General Mills", "Consumer Defensive"), ("ALL", "Allstate Corp.", "Financial Services"),
    ("MCHP", "Microchip Technology", "Technology"), ("BK", "Bank of New York Mellon", "Financial Services"),
    ("XEL", "Xcel Energy", "Utilities"), ("MSCI", "MSCI Inc.", "Financial Services"),
    ("DXCM", "DexCom Inc.", "Healthcare"), ("CMI", "Cummins Inc.", "Industrials"),
    ("WELL", "Welltower Inc.", "Real Estate"), ("DELL", "Dell Technologies", "Technology"),
    ("RSG", "Republic Services", "Industrials"), ("HSY", "Hershey Co.", "Consumer Defensive"),
    ("DOW", "Dow Inc.", "Basic Materials"), ("NUE", "Nucor Corp.", "Basic Materials"),
    ("FAST", "Fastenal Co.", "Industrials"), ("KR", "Kroger Co.", "Consumer Defensive"),
    ("YUM", "Yum! Brands", "Consumer Cyclical"), ("OTIS", "Otis Worldwide", "Industrials"),
    ("PAYX", "Paychex Inc.", "Industrials"), ("VRSK", "Verisk Analytics", "Industrials"),
    ("KHC", "Kraft Heinz Co.", "Consumer Defensive"), ("EA", "Electronic Arts", "Communication Services"),
    ("CTVA", "Corteva Inc.", "Basic Materials"), ("DD", "DuPont de Nemours", "Basic Materials"),
    ("FIS", "Fidelity National Information", "Technology"), ("DAL", "Delta Air Lines", "Industrials"),
    ("ED", "Consolidated Edison", "Utilities"), ("VICI", "VICI Properties", "Real Estate"),
    ("AME", "AMETEK Inc.", "Industrials"), ("ON", "ON Semiconductor", "Technology"),
    ("KDP", "Keurig Dr Pepper", "Consumer Defensive"), ("HPQ", "HP Inc.", "Technology"),
    ("ODFL", "Old Dominion Freight Line", "Industrials"), ("LULU", "Lululemon Athletica", "Consumer Cyclical"),
    ("LHX", "L3Harris Technologies", "Industrials"), ("PCG", "PG&E Corp.", "Utilities"),
    ("KVUE", "Kenvue Inc.", "Consumer Defensive"), ("IT", "Gartner Inc.", "Technology"),
    ("ROK", "Rockwell Automation", "Industrials"), ("GEHC", "GE HealthCare Technologies", "Healthcare"),
    ("EXR", "Extra Space Storage", "Real Estate"), ("HES", "Hess Corp.", "Energy"),
    ("BIIB", "Biogen Inc.", "Healthcare"), ("IDXX", "IDEXX Laboratories", "Healthcare"),
    ("WEC", "WEC Energy Group", "Utilities"), ("FANG", "Diamondback Energy", "Energy"),
    ("CSGP", "CoStar Group", "Real Estate"), ("VMC", "Vulcan Materials", "Basic Materials"),
    ("MLM", "Martin Marietta Materials", "Basic Materials"), ("CHTR", "Charter Communications", "Communication Services"),
    ("STT", "State Street Corp.", "Financial Services"), ("EFX", "Equifax Inc.", "Industrials"),
    ("SYY", "Sysco Corp.", "Consumer Defensive"), ("RMD", "ResMed Inc.", "Healthcare"),
    ("ADM", "Archer-Daniels-Midland", "Consumer Defensive"), ("AVB", "AvalonBay Communities", "Real Estate"),
    ("EQR", "Equity Residential", "Real Estate"), ("CDW", "CDW Corp.", "Technology"),
    ("AWK", "American Water Works", "Utilities"), ("FITB", "Fifth Third Bancorp", "Financial Services"),
    ("HIG", "Hartford Financial Services", "Financial Services"), ("DTE", "DTE Energy", "Utilities"),
    ("XYL", "Xylem Inc.", "Industrials"), ("PWR", "Quanta Services", "Industrials"),
    ("MTB", "M&T Bank Corp.", "Financial Services"), ("NDAQ", "Nasdaq Inc.", "Financial Services"),
    ("ANSS", "ANSYS Inc.", "Technology"), ("VLTO", "Veralto Corp.", "Industrials"),
    ("PPG", "PPG Industries", "Basic Materials"), ("WBD", "Warner Bros. Discovery", "Communication Services"),
    ("WST", "West Pharmaceutical Services", "Healthcare"), ("KEYS", "Keysight Technologies", "Technology"),
    ("EBAY", "eBay Inc.", "Consumer Cyclical"), ("WAB", "Wabtec Corp.", "Industrials"),
    ("WTW", "Willis Towers Watson", "Financial Services"), ("RJF", "Raymond James Financial", "Financial Services"),
    ("BRO", "Brown & Brown", "Financial Services"), ("VTR", "Ventas Inc.", "Real Estate"),
    ("FE", "FirstEnergy Corp.", "Utilities"), ("HPE", "Hewlett Packard Enterprise", "Technology"),
    ("STLD", "Steel Dynamics", "Basic Materials"), ("ARE", "Alexandria Real Estate", "Real Estate"),
    ("LYB", "LyondellBasell Industries", "Basic Materials"), ("LDOS", "Leidos Holdings", "Industrials"),
    ("CAH", "Cardinal Health", "Healthcare"), ("CNP", "CenterPoint Energy", "Utilities"),
    ("TROW", "T. Rowe Price Group", "Financial Services"), ("BAX", "Baxter International", "Healthcare"),
    ("BBY", "Best Buy Co.", "Consumer Cyclical"), ("CINF", "Cincinnati Financial", "Financial Services"),
    ("PHM", "PulteGroup Inc.", "Consumer Cyclical"), ("DOV", "Dover Corp.", "Industrials"),
    ("TYL", "Tyler Technologies", "Technology"), ("CBRE", "CBRE Group", "Real Estate"),
    ("ES", "Eversource Energy", "Utilities"), ("NTRS", "Northern Trust Corp.", "Financial Services"),
    ("ETR", "Entergy Corp.", "Utilities"), ("WY", "Weyerhaeuser Co.", "Real Estate"),
    ("GWW", "W.W. Grainger", "Industrials"), ("HBAN", "Huntington Bancshares", "Financial Services"),
    ("CFG", "Citizens Financial Group", "Financial Services"), ("ATO", "Atmos Energy", "Utilities"),
    ("DGX", "Quest Diagnostics", "Healthcare"), ("DLTR", "Dollar Tree Inc.", "Consumer Defensive"),
    ("INVH", "Invitation Homes", "Real Estate"), ("LH", "Labcorp Holdings", "Healthcare"),
    ("EXPD", "Expeditors International", "Industrials"), ("STE", "STERIS plc", "Healthcare"),
    ("ZBH", "Zimmer Biomet Holdings", "Healthcare"), ("PPL", "PPL Corp.", "Utilities"),
    ("MRO", "Marathon Oil", "Energy"), ("HOLX", "Hologic Inc.", "Healthcare"),
    ("TSCO", "Tractor Supply Co.", "Consumer Cyclical"), ("DVN", "Devon Energy", "Energy"),
    ("UAL", "United Airlines", "Industrials"), ("AAL", "American Airlines", "Industrials"),
    ("LUV", "Southwest Airlines", "Industrials"), ("CCL", "Carnival Corp.", "Consumer Cyclical"),
    ("RCL", "Royal Caribbean Cruises", "Consumer Cyclical"), ("NCLH", "Norwegian Cruise Line", "Consumer Cyclical"),
    ("SNAP", "Snap Inc.", "Communication Services"), ("PINS", "Pinterest Inc.", "Communication Services"),
    ("SQ", "Block Inc.", "Technology"), ("SHOP", "Shopify Inc.", "Technology"),
    ("UBER", "Uber Technologies", "Technology"), ("LYFT", "Lyft Inc.", "Technology"),
    ("ABNB", "Airbnb Inc.", "Consumer Cyclical"), ("DASH", "DoorDash Inc.", "Consumer Cyclical"),
    ("RBLX", "Roblox Corp.", "Communication Services"), ("PLTR", "Palantir Technologies", "Technology"),
    ("SNOW", "Snowflake Inc.", "Technology"), ("DDOG", "Datadog Inc.", "Technology"),
    ("CRWD", "CrowdStrike Holdings", "Technology"), ("NET", "Cloudflare Inc.", "Technology"),
    ("MDB", "MongoDB Inc.", "Technology"), ("ZS", "Zscaler Inc.", "Technology"),
    ("OKTA", "Okta Inc.", "Technology"), ("TEAM", "Atlassian Corp.", "Technology"),
    ("ZM", "Zoom Video Communications", "Technology"), ("DOCU", "DocuSign Inc.", "Technology"),
    ("HOOD", "Robinhood Markets", "Financial Services"), ("COIN", "Coinbase Global", "Financial Services"),
    ("MSTR", "MicroStrategy Inc.", "Technology"), ("RIVN", "Rivian Automotive", "Consumer Cyclical"),
    ("LCID", "Lucid Group", "Consumer Cyclical"), ("NIO", "NIO Inc.", "Consumer Cyclical"),
    ("XPEV", "XPeng Inc.", "Consumer Cyclical"), ("LI", "Li Auto Inc.", "Consumer Cyclical"),
    ("BABA", "Alibaba Group", "Consumer Cyclical"), ("JD", "JD.com Inc.", "Consumer Cyclical"),
    ("PDD", "PDD Holdings", "Consumer Cyclical"), ("BIDU", "Baidu Inc.", "Communication Services"),
    ("TSM", "Taiwan Semiconductor", "Technology"), ("ASML", "ASML Holding", "Technology"),
    ("SAP", "SAP SE", "Technology"), ("NVO", "Novo Nordisk", "Healthcare"),
    ("SHEL", "Shell plc", "Energy"), ("BP", "BP plc", "Energy"),
    ("HSBC", "HSBC Holdings", "Financial Services"), ("UL", "Unilever plc", "Consumer Defensive"),
    ("TM", "Toyota Motor Corp.", "Consumer Cyclical"), ("SONY", "Sony Group Corp.", "Consumer Cyclical"),
    ("HMC", "Honda Motor Co.", "Consumer Cyclical"), ("MUFG", "Mitsubishi UFJ Financial", "Financial Services"),
    ("RIO", "Rio Tinto plc", "Basic Materials"), ("BHP", "BHP Group", "Basic Materials"),
    ("BTI", "British American Tobacco", "Consumer Defensive"), ("DEO", "Diageo plc", "Consumer Defensive"),
    ("AZN", "AstraZeneca plc", "Healthcare"), ("GSK", "GSK plc", "Healthcare"),
    ("NVS", "Novartis AG", "Healthcare"), ("RHHBY", "Roche Holding AG", "Healthcare"),
    ("PLNT", "Planet Fitness", "Consumer Cyclical"), ("WBA", "Walgreens Boots Alliance", "Healthcare"),
    ("AAP", "Advance Auto Parts", "Consumer Cyclical"), ("MGM", "MGM Resorts International", "Consumer Cyclical"),
    ("WYNN", "Wynn Resorts", "Consumer Cyclical"), ("LVS", "Las Vegas Sands", "Consumer Cyclical"),
    ("DKNG", "DraftKings Inc.", "Consumer Cyclical"), ("PENN", "PENN Entertainment", "Consumer Cyclical"),
    ("CZR", "Caesars Entertainment", "Consumer Cyclical"), ("BMRN", "BioMarin Pharmaceutical", "Healthcare"),
    ("ALGN", "Align Technology", "Healthcare"), ("ILMN", "Illumina Inc.", "Healthcare"),
    ("MRNA", "Moderna Inc.", "Healthcare"), ("BNTX", "BioNTech SE", "Healthcare"),
    ("NVAX", "Novavax Inc.", "Healthcare"), ("PYC", "Pyrum Innovations", "Basic Materials"),
    ("ENPH", "Enphase Energy", "Technology"), ("SEDG", "SolarEdge Technologies", "Technology"),
    ("FSLR", "First Solar Inc.", "Technology"), ("PLUG", "Plug Power Inc.", "Industrials"),
    ("BE", "Bloom Energy", "Industrials"), ("CHPT", "ChargePoint Holdings", "Industrials"),
    ("RIVN", "Rivian Automotive", "Consumer Cyclical"),
    # ETFs
    ("SPY", "SPDR S&P 500 ETF", None), ("VOO", "Vanguard S&P 500 ETF", None),
    ("QQQ", "Invesco QQQ Trust", None), ("IVV", "iShares Core S&P 500 ETF", None),
    ("VTI", "Vanguard Total Stock Market ETF", None), ("VEA", "Vanguard FTSE Developed Markets", None),
    ("VWO", "Vanguard FTSE Emerging Markets", None), ("AGG", "iShares Core US Aggregate Bond", None),
    ("BND", "Vanguard Total Bond Market", None), ("IWM", "iShares Russell 2000 ETF", None),
    ("DIA", "SPDR Dow Jones Industrial Average", None), ("GLD", "SPDR Gold Shares", None),
    ("SLV", "iShares Silver Trust", None), ("TLT", "iShares 20+ Year Treasury Bond", None),
    ("HYG", "iShares iBoxx High Yield Corporate Bond", None), ("LQD", "iShares iBoxx Investment Grade Corporate Bond", None),
    ("XLF", "Financial Select Sector SPDR", None), ("XLK", "Technology Select Sector SPDR", None),
    ("XLE", "Energy Select Sector SPDR", None), ("XLV", "Health Care Select Sector SPDR", None),
    ("XLI", "Industrial Select Sector SPDR", None), ("XLY", "Consumer Discretionary Select SPDR", None),
    ("XLP", "Consumer Staples Select SPDR", None), ("XLU", "Utilities Select Sector SPDR", None),
    ("XLB", "Materials Select Sector SPDR", None), ("XLRE", "Real Estate Select Sector SPDR", None),
    ("XLC", "Communication Services Select SPDR", None), ("ARKK", "ARK Innovation ETF", None),
    ("ARKQ", "ARK Autonomous Tech & Robotics", None), ("ARKW", "ARK Next Generation Internet", None),
    ("SOXX", "iShares Semiconductor ETF", None), ("SMH", "VanEck Semiconductor ETF", None),
    ("IBB", "iShares Biotechnology ETF", None), ("XBI", "SPDR S&P Biotech ETF", None),
    ("KRE", "SPDR S&P Regional Banking", None), ("XHB", "SPDR S&P Homebuilders", None),
    ("XRT", "SPDR S&P Retail ETF", None), ("VNQ", "Vanguard Real Estate ETF", None),
    ("VYM", "Vanguard High Dividend Yield ETF", None), ("SCHD", "Schwab US Dividend Equity ETF", None),
    ("DGRO", "iShares Core Dividend Growth ETF", None), ("VIG", "Vanguard Dividend Appreciation ETF", None),
    ("EFA", "iShares MSCI EAFE ETF", None), ("EEM", "iShares MSCI Emerging Markets ETF", None),
    ("FXI", "iShares China Large-Cap ETF", None), ("EWJ", "iShares MSCI Japan ETF", None),
    ("INDA", "iShares MSCI India ETF", None), ("USO", "United States Oil Fund", None),
    ("UNG", "United States Natural Gas Fund", None), ("BITO", "ProShares Bitcoin Strategy ETF", None),
    ("IBIT", "iShares Bitcoin Trust", None), ("FBTC", "Fidelity Wise Origin Bitcoin Fund", None),
]

# Dedupe by symbol
_seen = set()
_unique = []
for t in TICKERS:
    if t[0] not in _seen:
        _seen.add(t[0])
        _unique.append(t)
TICKERS = _unique

TICKERS_DICT = {t[0]: {"symbol": t[0], "name": t[1], "sector": t[2]} for t in TICKERS}
TICKER_COUNT = len(TICKERS)
