import React from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { useTheme } from '../src/ThemeContext';

export default function Terms() {
  const { theme } = useTheme();
  const router = useRouter();
  const s = styles(theme);

  const sections: { h: string; p: string }[] = [
    { h: '1. Acceptance', p: 'By creating an account or using Pav, you agree to these Terms of Service and acknowledge that you have read and understood them.' },
    { h: '2. Not Financial Advice', p: 'Pav provides AI-generated predictions, analysis, and forecasts for informational and educational purposes only. Nothing in this app constitutes financial, investment, legal, or tax advice. We are not a licensed broker-dealer, investment adviser, or fiduciary. You should consult a qualified professional before making any investment decisions.' },
    { h: '3. AI Predictions Carry Uncertainty', p: 'Predictions are generated by machine-learning models combining statistical indicators (RSI, SMA, momentum, volatility) and large language model reasoning (Claude Sonnet 4.5). Past patterns do NOT guarantee future results. Market conditions change constantly, and AI models can be wrong — often significantly. Confidence scores indicate the model’s internal certainty, not actual probability of accuracy.' },
    { h: '4. No Guarantees', p: 'We make no guarantees regarding prediction accuracy, profitability, or any specific outcome. Markets are inherently volatile and unpredictable. You may lose money — including your entire investment — by acting on information in this app.' },
    { h: '5. Your Responsibility', p: 'You are solely responsible for your trading and investment decisions. Always do your own research (DYOR), understand the risks, and never invest more than you can afford to lose.' },
    { h: '6. Data Sources', p: 'Market data is provided by third-party providers (e.g., Finnhub). We do not guarantee real-time accuracy, completeness, or freshness of this data. Delays, errors, and outages may occur.' },
    { h: '7. Subscriptions & Billing', p: 'Premium subscriptions (monthly $4.99 / yearly $49.99) auto-renew until canceled. You can cancel any time from Settings. Partial-period refunds are not provided.' },
    { h: '8. Privacy', p: 'We store your email, password hash, watchlist, and alerts. We do not sell your data. Predictions you request are logged for model-quality auditing.' },
    { h: '9. Limitation of Liability', p: 'To the maximum extent permitted by law, Pav, its operators, and affiliates shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising from your use of the app or reliance on its predictions.' },
    { h: '10. Changes', p: 'We may update these Terms at any time. Continued use after changes constitutes acceptance of the updated Terms.' },
  ];

  return (
    <SafeAreaView style={s.safe} testID="terms-screen">
      <View style={s.header}>
        <TouchableOpacity testID="btn-close-terms" onPress={() => router.back()}>
          <Ionicons name="chevron-back" size={26} color={theme.textPrimary} />
        </TouchableOpacity>
        <Text style={[s.title, { color: theme.textPrimary }]}>Terms of Service</Text>
        <View style={{ width: 26 }} />
      </View>

      <ScrollView contentContainerStyle={{ padding: 20, paddingBottom: 60 }}>
        <View style={[s.warnBox, { borderColor: theme.bearish, backgroundColor: theme.bearishBg }]}>
          <Ionicons name="warning" size={22} color={theme.bearish} />
          <Text style={[s.warnText, { color: theme.textPrimary }]}>
            AI predictions are NOT financial advice. Markets are unpredictable. You may lose money. Always do your own research.
          </Text>
        </View>

        {sections.map((sec, i) => (
          <View key={i} style={{ marginTop: 24 }}>
            <Text style={[s.h, { color: theme.textPrimary }]}>{sec.h}</Text>
            <Text style={[s.p, { color: theme.textSecondary }]}>{sec.p}</Text>
          </View>
        ))}

        <Text style={[s.footer, { color: theme.textTertiary }]}>Last updated: Feb 2026 · Pav v1.0</Text>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = (t: any) => StyleSheet.create({
  safe: { flex: 1, backgroundColor: t.background },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: t.border },
  title: { fontSize: 17, fontWeight: '600' },
  warnBox: { flexDirection: 'row', padding: 14, borderRadius: 12, borderWidth: 1, gap: 10, alignItems: 'flex-start' },
  warnText: { flex: 1, fontSize: 13, lineHeight: 19, fontWeight: '500' },
  h: { fontSize: 16, fontWeight: '700', marginBottom: 6 },
  p: { fontSize: 14, lineHeight: 21 },
  footer: { fontSize: 12, textAlign: 'center', marginTop: 40 },
});
