import { Navbar } from '@/components/Navbar';
import { Footer, CONTACT_EMAIL } from '@/components/Footer';

export const metadata = {
  title: 'Terms of Service — Pav',
  description: 'The rules of the road for using Pav.',
};

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="max-w-3xl mx-auto container-px py-20">
        <h1 className="text-4xl md:text-5xl font-bold tracking-tight gradient-text mb-4">
          Terms of Service
        </h1>
        <p className="text-text-tertiary text-sm mb-12">Last updated: November 2025</p>

        <Section title="1. Agreement">
          <p>
            By creating an account, downloading, or using the Pav application (the &ldquo;Service&rdquo;), you agree to be bound by these Terms of Service (&ldquo;Terms&rdquo;). If you do not agree, do not use the Service.
          </p>
        </Section>

        <Section title="2. Not financial advice">
          <p>
            <strong className="text-text-primary">Pav is for informational and educational purposes only.</strong> Predictions, indicators, and any content shown in the app are generated by automated systems (including AI models) and may be inaccurate, incomplete, or out of date.
          </p>
          <p>
            Pav does not provide investment, tax, legal, or financial advice, and is not a registered broker-dealer or investment adviser. Nothing in the Service constitutes a recommendation to buy, sell, or hold any security or asset. Past performance does not guarantee future results. Always do your own research and consult a qualified financial professional before making investment decisions.
          </p>
        </Section>

        <Section title="3. Eligibility">
          <p>
            You must be at least 18 years old and legally able to enter into a binding contract in your jurisdiction. By using Pav, you represent that you meet these requirements.
          </p>
        </Section>

        <Section title="4. Your account">
          <p>
            You are responsible for keeping your login credentials confidential and for all activity under your account. Notify us immediately at <a href={`mailto:${CONTACT_EMAIL}`} className="text-indigo hover:underline">{CONTACT_EMAIL}</a> of any unauthorized use.
          </p>
        </Section>

        <Section title="5. Subscriptions and billing">
          <p>
            Pav offers a Free tier and a Premium tier ($4.99/month or $49.99/year). Premium is billed in advance through your platform&rsquo;s app store and renews automatically until cancelled. You can cancel any time through your App Store or Play Store subscription settings; cancellation takes effect at the end of the current billing period.
          </p>
          <p>
            All fees are non-refundable except where required by law.
          </p>
        </Section>

        <Section title="6. Acceptable use">
          <p>You agree not to:</p>
          <ul className="list-disc list-inside space-y-1 ml-2">
            <li>Reverse engineer, decompile, or scrape any part of the Service.</li>
            <li>Use the Service to violate any law or third-party right.</li>
            <li>Resell, sublicense, or commercially redistribute predictions, data, or content from Pav.</li>
            <li>Interfere with or disrupt the integrity or performance of the Service.</li>
          </ul>
        </Section>

        <Section title="7. Intellectual property">
          <p>
            The Service, including all software, design, branding, and content (excluding third-party market data), is owned by Pav and protected by intellectual-property laws. We grant you a limited, non-exclusive, non-transferable license to use the app for personal, non-commercial purposes.
          </p>
        </Section>

        <Section title="8. Third-party data">
          <p>
            Market data is provided by third parties (Finnhub, Yahoo Finance and others). We do not warrant the accuracy, completeness, or timeliness of any data and are not liable for any errors, delays, or omissions.
          </p>
        </Section>

        <Section title="9. Disclaimers">
          <p>
            THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE,&rdquo; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING (BUT NOT LIMITED TO) MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
          </p>
        </Section>

        <Section title="10. Limitation of liability">
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, PAV AND ITS AFFILIATES WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY TRADING LOSSES, ARISING OUT OF OR RELATING TO YOUR USE OF THE SERVICE.
          </p>
        </Section>

        <Section title="11. Termination">
          <p>
            We may suspend or terminate your access to the Service at any time, with or without notice, if you violate these Terms or for any other reason. You may stop using the Service and delete your account at any time.
          </p>
        </Section>

        <Section title="12. Changes to the Service or Terms">
          <p>
            We may modify the Service or these Terms at any time. Material changes will be communicated in-app or by email. Continued use of the Service after changes take effect constitutes acceptance.
          </p>
        </Section>

        <Section title="13. Governing law">
          <p>
            These Terms are governed by the laws of the jurisdiction in which Pav is operated, without regard to its conflict-of-law principles.
          </p>
        </Section>

        <Section title="14. Contact">
          <p>
            Questions about these Terms? Email <a href={`mailto:${CONTACT_EMAIL}`} className="text-indigo hover:underline">{CONTACT_EMAIL}</a>.
          </p>
        </Section>
      </main>
      <Footer />
    </>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-xl md:text-2xl font-semibold text-text-primary mb-3">{title}</h2>
      <div className="text-text-secondary leading-relaxed space-y-3 text-[15px]">{children}</div>
    </section>
  );
}
